config/routes.rb
Rails.application.routes.draw do
  resources :selected_sizes

  resources :applied_sizes

  resources :item_sizes

  resources :applied_labels

  resources :labels

  resources :selected_modifiers

  resources :applied_mod_groups

  resources :grouped_modifiers

  resources :modifiers

  resources :modifier_groups

  resources :categorizations

  resources :categories

  resources :taxes

  resources :items

  resources :cart_items do
    collection do
      get :cart
    end
  end

  resources :selected_addresses

  resources :orders do
     collection do
       get :confirmation
     end
   end

  resources :addresses

  devise_for :users
  
  root :to => 'pages#landing'
  
  get "pages/menu" # , as: :menu # example of fancy route... doesn't affect the url though
  get "pages/landing"
  get "pages/select"
  get "pages/payment" # going to want a POST for the API, right? ex: post 'miners/lease' => 'miners#btcpayment'

  post 'cart_items/cart' => 'cart_items#add_to_cart'
  

  

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
end

app/models/applied_label.rb
class AppliedLabel < ActiveRecord::Base
  has_one :label
  belongs_to :item
  belongs_to :cart_item
end

app/models/applied_size.rb
class AppliedSize < ActiveRecord::Base
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :order
  belongs_to :user
  has_many :selected_modifiers, dependent: :destroy
  
  accepts_nested_attributes_for :item
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :item
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations
end

app/models/grouped_modifier.rb
class GroupedModifier < ActiveRecord::Base
  belongs_to :modifer_group
  belongs_to :modifiers
  
  # This could possibly be deprecated, using has_and_belongs_to_many instead for the modifier and modifier_group models
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :categorization
  has_many :cart_items
  has_many :applied_labels
  has_many :applied_mod_groups
end

app/models/item_size.rb
class ItemSize < ActiveRecord::Base
end

app/models/label.rb
class Label < ActiveRecord::Base
  belongs_to :applied_label
end

app/models/modifier.rb
class Modifier < ActiveRecord::Base
  mount_uploader :file, ToppingUploader
end

app/models/modifier_group.rb
class ModifierGroup < ActiveRecord::Base
  has_many :modifiers, through: :grouped_modifiers
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :cart_items
  has_one :selected_address
end

app/models/selected_address.rb
class SelectedAddress < ActiveRecord::Base
  belongs_to :order
end

app/models/selected_size.rb
class SelectedSize < ActiveRecord::Base
end

app/models/tax.rb
class Tax < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :addresses
  has_many :orders
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_label, only: [:show, :edit, :update, :destroy]

  # GET /labels
  # GET /labels.json
  def index
    @labels = Label.all
  end

  # GET /labels/1
  # GET /labels/1.json
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels
  # POST /labels.json
  def create
    @label = Label.new(label_params)

    respond_to do |format|
      if @label.save
        format.html { redirect_to @label, notice: 'Label was successfully created.' }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1
  # PATCH/PUT /labels/1.json
  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to @label, notice: 'Label was successfully updated.' }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1
  # DELETE /labels/1.json
  def destroy
    @label.destroy
    respond_to do |format|
      format.html { redirect_to labels_url, notice: 'Label was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def label_params
      params.require(:label).permit(:name)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  def reverse(a)
      (0...(a.length/2)).each {|i| a[i], a[a.length-i-1]=a[a.length-i-1], a[i]}
      return a
  end
  
end

app/helpers/taxes_helper.rb
module TaxesHelper
end

app/views/labels/_form.html.erb
<%= form_for(@label) do |f| %>
  <% if @label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
      <% @label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/labels/edit.html.erb
<h1>Editing label</h1>

<%= render 'form' %>

<%= link_to 'Show', @label %> |
<%= link_to 'Back', labels_path %>

app/views/labels/index.html.erb
<h1>Listing labels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= label.name %></td>
        <td><%= link_to 'Show', label %></td>
        <td><%= link_to 'Edit', edit_label_path(label) %></td>
        <td><%= link_to 'Destroy', label, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Label', new_label_path %>

app/views/labels/new.html.erb
<h1>New label</h1>

<%= render 'form' %>

<%= link_to 'Back', labels_path %>

app/views/labels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @label.name %>
</p>

<%= link_to 'Edit', edit_label_path(@label) %> |
<%= link_to 'Back', labels_path %>