config/routes.rb
Rails.application.routes.draw do
  resources :selected_sizes

  resources :applied_sizes

  resources :item_sizes

  resources :applied_labels

  resources :labels

  resources :selected_modifiers

  resources :applied_mod_groups

  resources :grouped_modifiers

  resources :modifiers

  resources :modifier_groups

  resources :categorizations

  resources :categories

  resources :taxes

  resources :items

  resources :cart_items do
    collection do
      get :cart
    end
  end

  resources :selected_addresses

  resources :orders do
     collection do
       get :confirmation
     end
   end

  resources :addresses

  devise_for :users
  
  root :to => 'pages#landing'
  
  get "pages/menu" # , as: :menu # example of fancy route... doesn't affect the url though
  get "pages/landing"
  get "pages/select"
  get "pages/payment" # going to want a POST for the API, right? ex: post 'miners/lease' => 'miners#btcpayment'

  post 'cart_items/cart' => 'cart_items#add_to_cart'
  

  

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
end

app/models/applied_label.rb
class AppliedLabel < ActiveRecord::Base
  has_one :label
  belongs_to :item
  belongs_to :cart_item
end

app/models/applied_mod_group.rb
class AppliedModGroup < ActiveRecord::Base
  belongs_to :item
  has_one :modifier_group
end

app/models/applied_size.rb
class AppliedSize < ActiveRecord::Base
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :order
  belongs_to :user
  has_many :selected_modifiers, dependent: :destroy
  
  accepts_nested_attributes_for :item
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :item
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :categorization
  has_many :cart_items
  has_many :applied_labels
  has_many :applied_mod_groups
end

app/models/item_size.rb
class ItemSize < ActiveRecord::Base
end

app/models/label.rb
class Label < ActiveRecord::Base
  belongs_to :applied_label
end

app/models/modifier.rb
class Modifier < ActiveRecord::Base
  mount_uploader :file, ToppingUploader
end

app/models/modifier_group.rb
class ModifierGroup < ActiveRecord::Base
  has_many :modifiers, through: :grouped_modifiers
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :cart_items
  has_one :selected_address
end

app/models/selected_size.rb
class SelectedSize < ActiveRecord::Base
end

app/models/tax.rb
class Tax < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :addresses
  has_many :orders
end

app/controllers/applied_mod_groups_controller.rb
class AppliedModGroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_applied_mod_group, only: [:show, :edit, :update, :destroy]

  # GET /applied_mod_groups
  # GET /applied_mod_groups.json
  def index
    @applied_mod_groups = AppliedModGroup.all
  end

  # GET /applied_mod_groups/1
  # GET /applied_mod_groups/1.json
  def show
  end

  # GET /applied_mod_groups/new
  def new
    @modifier_groups = ModifierGroup.all
    @items = Item.all
    @applied_mod_group = AppliedModGroup.new
  end

  # GET /applied_mod_groups/1/edit
  def edit
    @modifier_groups = ModifierGroup.all
    @items = Item.all
  end

  # POST /applied_mod_groups
  # POST /applied_mod_groups.json
  def create
    @applied_mod_group = AppliedModGroup.new(applied_mod_group_params)

    respond_to do |format|
      if @applied_mod_group.save
        format.html { redirect_to @applied_mod_group, notice: 'Applied mod group was successfully created.' }
        format.json { render :show, status: :created, location: @applied_mod_group }
      else
        format.html { render :new }
        format.json { render json: @applied_mod_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applied_mod_groups/1
  # PATCH/PUT /applied_mod_groups/1.json
  def update
    respond_to do |format|
      if @applied_mod_group.update(applied_mod_group_params)
        format.html { redirect_to @applied_mod_group, notice: 'Applied mod group was successfully updated.' }
        format.json { render :show, status: :ok, location: @applied_mod_group }
      else
        format.html { render :edit }
        format.json { render json: @applied_mod_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applied_mod_groups/1
  # DELETE /applied_mod_groups/1.json
  def destroy
    @applied_mod_group.destroy
    respond_to do |format|
      format.html { redirect_to applied_mod_groups_url, notice: 'Applied mod group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applied_mod_group
      @applied_mod_group = AppliedModGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applied_mod_group_params
      params.require(:applied_mod_group).permit(:modifier_group_id, :item_id)
    end
end

app/helpers/applied_mod_groups_helper.rb
module AppliedModGroupsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  def reverse(a)
      (0...(a.length/2)).each {|i| a[i], a[a.length-i-1]=a[a.length-i-1], a[i]}
      return a
  end
  
end

app/helpers/taxes_helper.rb
module TaxesHelper
end

app/views/applied_mod_groups/_form.html.erb
<%= form_for(@applied_mod_group) do |f| %>
  <% if @applied_mod_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@applied_mod_group.errors.count, "error") %> prohibited this applied_mod_group from being saved:</h2>

      <ul>
      <% @applied_mod_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :modifier_group_id %><br>
    <%= f.select :modifier_group_id, options_from_collection_for_select(@modifier_groups, "id", "name", @applied_mod_group.modifier_group_id), {}, class: "form-control", :prompt => "Select modifier group" %>
  </div>
  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.select :item_id, options_from_collection_for_select(@items, "id", "name", @applied_mod_group.item_id), {}, class: "form-control", :prompt => "Select item" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applied_mod_groups/edit.html.erb
<h1>Editing applied_mod_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @applied_mod_group %> |
<%= link_to 'Back', applied_mod_groups_path %>

app/views/applied_mod_groups/index.html.erb
<h1>Listing applied_mod_groups</h1>

<table>
  <thead>
    <tr>
      <th>Modifier group</th>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applied_mod_groups.each do |applied_mod_group| %>
      <tr>
        <td><%= applied_mod_group.modifier_group_id %></td>
        <td><%= applied_mod_group.item_id %></td>
        <td><%= link_to 'Show', applied_mod_group %></td>
        <td><%= link_to 'Edit', edit_applied_mod_group_path(applied_mod_group) %></td>
        <td><%= link_to 'Destroy', applied_mod_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Applied mod group', new_applied_mod_group_path %>

app/views/applied_mod_groups/new.html.erb
<h1>New applied_mod_group</h1>

<%= render 'form' %>

<%= link_to 'Back', applied_mod_groups_path %>

app/views/applied_mod_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Modifier group:</strong>
  <%= @applied_mod_group.modifier_group_id %>
</p>

<p>
  <strong>Item:</strong>
  <%= @applied_mod_group.item_id %>
</p>

<%= link_to 'Edit', edit_applied_mod_group_path(@applied_mod_group) %> |
<%= link_to 'Back', applied_mod_groups_path %>