config/routes.rb
Rails.application.routes.draw do
  resources :selected_sizes

  resources :applied_sizes

  resources :item_sizes

  resources :applied_labels

  resources :labels

  resources :selected_modifiers

  resources :applied_mod_groups

  resources :grouped_modifiers

  resources :modifiers

  resources :modifier_groups

  resources :categorizations

  resources :categories

  resources :taxes

  resources :items

  resources :cart_items do
    collection do
      get :cart
    end
  end

  resources :selected_addresses

  resources :orders do
     collection do
       get :confirmation
     end
   end

  resources :addresses

  devise_for :users
  
  root :to => 'pages#landing'
  
  get "pages/menu" # , as: :menu # example of fancy route... doesn't affect the url though
  get "pages/landing"
  get "pages/select"
  get "pages/payment" # going to want a POST for the API, right? ex: post 'miners/lease' => 'miners#btcpayment'

  post 'cart_items/cart' => 'cart_items#add_to_cart'
  

  

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
end

app/models/applied_label.rb
class AppliedLabel < ActiveRecord::Base
  has_one :label
  belongs_to :item
  belongs_to :cart_item
end

app/models/applied_size.rb
class AppliedSize < ActiveRecord::Base
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :order
  belongs_to :user
  has_many :selected_modifiers, dependent: :destroy
  
  accepts_nested_attributes_for :item
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :item
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations
end

app/models/grouped_modifier.rb
class GroupedModifier < ActiveRecord::Base
  belongs_to :modifer_group
  belongs_to :modifiers
  
  # This could possibly be deprecated, using has_and_belongs_to_many instead for the modifier and modifier_group models
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :categorization
  has_many :cart_items
  has_many :applied_labels
  has_many :applied_mod_groups
end

app/models/item_size.rb
class ItemSize < ActiveRecord::Base
end

app/models/label.rb
class Label < ActiveRecord::Base
  belongs_to :applied_label
end

app/models/modifier.rb
class Modifier < ActiveRecord::Base
  mount_uploader :file, ToppingUploader
end

app/models/modifier_group.rb
class ModifierGroup < ActiveRecord::Base
  has_many :modifiers, through: :grouped_modifiers
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :cart_items
  has_one :selected_address
end

app/models/selected_size.rb
class SelectedSize < ActiveRecord::Base
end

app/models/tax.rb
class Tax < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :addresses
  has_many :orders
end

app/controllers/applied_labels_controller.rb
class AppliedLabelsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_applied_label, only: [:show, :edit, :update, :destroy]

  # GET /applied_labels
  # GET /applied_labels.json
  def index
    @applied_labels = AppliedLabel.all
  end

  # GET /applied_labels/1
  # GET /applied_labels/1.json
  def show
  end

  # GET /applied_labels/new
  def new
    @items = Item.all
    @labels = Label.all
    @applied_label = AppliedLabel.new
  end

  # GET /applied_labels/1/edit
  def edit
    @items = Item.all
    @labels = Label.all
  end

  # POST /applied_labels
  # POST /applied_labels.json
  def create
    @applied_label = AppliedLabel.new(applied_label_params)

    respond_to do |format|
      if @applied_label.save
        format.html { redirect_to @applied_label, notice: 'Applied label was successfully created.' }
        format.json { render :show, status: :created, location: @applied_label }
      else
        format.html { render :new }
        format.json { render json: @applied_label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applied_labels/1
  # PATCH/PUT /applied_labels/1.json
  def update
    respond_to do |format|
      if @applied_label.update(applied_label_params)
        format.html { redirect_to @applied_label, notice: 'Applied label was successfully updated.' }
        format.json { render :show, status: :ok, location: @applied_label }
      else
        format.html { render :edit }
        format.json { render json: @applied_label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applied_labels/1
  # DELETE /applied_labels/1.json
  def destroy
    @applied_label.destroy
    respond_to do |format|
      format.html { redirect_to applied_labels_url, notice: 'Applied label was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applied_label
      @applied_label = AppliedLabel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applied_label_params
      params.require(:applied_label).permit(:item_id, :label_id, :daily_special, :day)
    end
end

app/helpers/applied_labels_helper.rb
module AppliedLabelsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  def reverse(a)
      (0...(a.length/2)).each {|i| a[i], a[a.length-i-1]=a[a.length-i-1], a[i]}
      return a
  end
  
end

app/helpers/taxes_helper.rb
module TaxesHelper
end

app/views/applied_labels/_form.html.erb
<%= form_for(@applied_label) do |f| %>
  <% if @applied_label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@applied_label.errors.count, "error") %> prohibited this applied_label from being saved:</h2>

      <ul>
      <% @applied_label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.select :item_id, options_from_collection_for_select(@items, "id", "name", @applied_label.item_id), {}, class: "form-control", :prompt => "Select item" %>
  </div>
  <div class="field">
    <%= f.label :label_id %><br>
    <%= f.select :label_id, options_from_collection_for_select(@labels, "id", "name", @applied_label.label_id), {}, class: "form-control", :prompt => "Select label" %>
  </div>
  <div class="field">
    <%= f.label :daily_special %><br>
    <%= f.check_box :daily_special %>
  </div>
  <div class="field">
    <%= f.label :day %><br>
    <%= f.select :day, options_for_select([["None","-1"],["Sunday", "0"], ["Monday", "1"], ["Tuesday","2"],["Wednesday","3"],["Thursday","4"],["Friday","5"],["Saturday","6"]],@applied_label.day), {}, {:class => "form-control"} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applied_labels/edit.html.erb
<h1>Editing applied_label</h1>

<%= render 'form' %>

<%= link_to 'Show', @applied_label %> |
<%= link_to 'Back', applied_labels_path %>

app/views/applied_labels/index.html.erb
<h1>Listing applied_labels</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Label</th>
      <th>Daily special</th>
      <th>Day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applied_labels.each do |applied_label| %>
      <tr>
        <td><%= applied_label.item_id %></td>
        <td><%= applied_label.label_id %></td>
        <td><%= applied_label.daily_special %></td>
        <td><%= applied_label.day %></td>
        <td><%= link_to 'Show', applied_label %></td>
        <td><%= link_to 'Edit', edit_applied_label_path(applied_label) %></td>
        <td><%= link_to 'Destroy', applied_label, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Applied label', new_applied_label_path %>

app/views/applied_labels/new.html.erb
<h1>New applied_label</h1>

<%= render 'form' %>

<%= link_to 'Back', applied_labels_path %>

app/views/applied_labels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @applied_label.item_id %>
</p>

<p>
  <strong>Label:</strong>
  <%= @applied_label.label_id %>
</p>

<p>
  <strong>Daily special:</strong>
  <%= @applied_label.daily_special %>
</p>

<p>
  <strong>Day:</strong>
  <%= @applied_label.day %>
</p>

<%= link_to 'Edit', edit_applied_label_path(@applied_label) %> |
<%= link_to 'Back', applied_labels_path %>